name: Go Test

on:
  push:
    branches:
      - main # Change this to the branch you want to run tests on
  pull_request: # Optional: Runs on PRs too
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.5 #

      - name: Run tests
        run: go test ./...
